const ADMIN_EMAIL='danielosabas045@gmail.com';
const STORE='ema_database_workspace_v3';
let data=JSON.parse(localStorage.getItem(STORE)||'{"users":[],"records":[],"invites":[]}');
let page='dashboard';
const root=document.getElementById('root');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(STORE,JSON.stringify(data))}
function shell(title,subtitle,body){root.innerHTML=`<div class="app"><aside class="sidebar"><div class="brand"><div class="mark">E</div><div><b>EMA DATABASE</b><small>Shared workspace</small></div></div><div class="nav">${[['dashboard','Panel'],['users','Usuarios'],['records','Base de datos'],['invites','Invitaciones'],['settings','Configuración']].map(x=>`<button class="${page===x[0]?'active':''}" data-page="${x[0]}">${x[1]}</button>`).join('')}</div><div class="adminbox"><b>ADMINISTRADOR</b><small>${ADMIN_EMAIL}</small><small>Acceso directo al espacio.</small></div></aside><main class="main"><header class="top"><div><h1>${title}</h1><p>${subtitle}</p></div><div class="account"><div><b>Administrador</b><small>${ADMIN_EMAIL}</small></div><div class="avatar">AD</div></div></header><section class="content">${body}</section></main></div>`;
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()})}
function dashboard(){return shell('Panel principal','Tu espacio está vacío y listo para empezar.',`<div class="grid"><div class="card kpi"><small>Usuarios</small><strong>${data.users.length}</strong><span>cuentas agregadas</span></div><div class="card kpi"><small>Registros</small><strong>${data.records.length}</strong><span>datos almacenados</span></div><div class="card kpi"><small>Invitaciones</small><strong>${data.invites.length}</strong><span>preparadas</span></div><div class="card kpi"><small>Estado</small><strong style="font-size:20px">LISTO</strong><span>espacio activo</span></div></div><div class="two section"><div class="card"><div class="head"><div><h2>Agregar usuario</h2><p>Agregá una persona al espacio.</p></div><button class="btn primary" onclick="openModal()">+ Agregar usuario</button></div><div class="empty"><div class="icon">👤</div><h3>${data.users.length?'Usuarios agregados':'Aún no hay usuarios'}</h3><p>${data.users.length?'Podés administrarlos desde la sección Usuarios.':'La base comienza vacía, tal como pediste.'}</p></div></div><div class="card"><div class="head"><div><h2>Cómo funciona</h2><p>Espacio compartido.</p></div></div><div class="statline"><span>Administrador</span><b>${ADMIN_EMAIL}</b></div><div class="statline"><span>Usuarios</span><b>Invitación individual</b></div><div class="statline"><span>Datos</span><b>Registros compartidos</b></div><div class="notice">Entrás directamente al panel, sin formulario de inicio de sesión.</div></div></div>`)}
function users(){return shell('Usuarios','Personas que tendrán acceso.',`<div class="head"><div><h2>Usuarios</h2><p>La lista empieza vacía.</p></div><button class="btn primary" onclick="openModal()">+ Agregar usuario</button></div><div class="card section">${data.users.length?`<table class="table"><thead><tr><th>Correo</th><th>Rol</th><th>Estado</th><th>Creado</th></tr></thead><tbody>${data.users.map(u=>`<tr><td>${esc(u.email)}</td><td>${esc(u.role)}</td><td><span class="badge pending">${esc(u.status)}</span></td><td>${esc(u.created)}</td></tr>`).join('')}</tbody></table>`:`<div class="empty"><div class="icon">👥</div><h3>No hay usuarios</h3><p>Usá “Agregar usuario” para comenzar.</p></div>`}</div>`)}
function records(){return shell('Base de datos','Registros del espacio.',`<div class="card"><div class="head"><div><h2>Registros</h2><p>Empieza completamente vacía.</p></div><button class="btn primary" onclick="addRecord()">+ Agregar registro</button></div>${data.records.length?`<table class="table"><thead><tr><th>Usuario</th><th>Fecha</th><th>Nombre</th><th>Descripción</th></tr></thead><tbody>${data.records.map(r=>`<tr><td>${esc(r.user)}</td><td>${esc(r.date)}</td><td>${esc(r.name)}</td><td>${esc(r.description)}</td></tr>`).join('')}</tbody></table>`:`<div class="empty"><div class="icon">▦</div><h3>No hay datos</h3><p>Agregá registros cuando comencés a trabajar.</p></div>`}</div>`)}
function invites(){return shell('Invitaciones','Historial de invitaciones.',`<div class="card">${data.invites.length?`<table class="table"><thead><tr><th>Correo</th><th>Rol</th><th>Estado</th></tr></thead><tbody>${data.invites.map(i=>`<tr><td>${esc(i.email)}</td><td>${esc(i.role)}</td><td><span class="badge pending">${esc(i.status)}</span></td></tr>`).join('')}</tbody></table>`:`<div class="empty"><div class="icon">✉</div><h3>No hay invitaciones</h3><p>Las invitaciones aparecerán aquí.</p><button class="btn primary" style="margin-top:16px" onclick="openModal()">Agregar usuario</button></div>`}</div>`)}
function settings(){return shell('Configuración','Datos principales del espacio.',`<div class="card"><div class="statline"><span>Administrador</span><b>${ADMIN_EMAIL}</b></div><div class="statline"><span>Acceso</span><b>Directo, sin inicio de sesión</b></div><div class="statline"><span>Persistencia</span><b>Este navegador</b></div><div class="notice">La interfaz funciona directamente. Para que usuarios y registros sean compartidos entre dispositivos y para enviar invitaciones reales por Gmail, hace falta publicar el backend.</div><button class="btn danger" onclick="clearAll()">Vaciar datos</button></div>`)}
function render(){if(page==='users')users();else if(page==='records')records();else if(page==='invites')invites();else if(page==='settings')settings();else dashboard()}
function openModal(){const old=document.getElementById('modal');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal open" id="modal"><div class="modal-box"><h2>Agregar usuario</h2><p style="color:var(--muted);font-size:11px;line-height:1.6">Ingresá el correo de la persona que tendrá acceso.</p><div class="form"><div><label>Correo electrónico</label><input id="emailInput" type="email" placeholder="persona@gmail.com"></div><div><label>Rol</label><select id="roleInput"><option>Usuario</option><option>Moderador</option></select></div></div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="addUser()">Agregar usuario</button></div></div></div>`);setTimeout(()=>document.getElementById('emailInput')?.focus(),20)}
function closeModal(){document.getElementById('modal')?.remove()}
function addUser(){const email=document.getElementById('emailInput')?.value.trim().toLowerCase();const role=document.getElementById('roleInput')?.value||'Usuario';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email||''))return alert('Ingresá un correo válido.');if(email===ADMIN_EMAIL)return alert('Ese correo ya es el administrador.');if(data.users.some(u=>u.email===email))return alert('Ese usuario ya existe.');data.users.push({email,role,status:'Pendiente',created:new Date().toLocaleDateString('es-GT')});data.invites.push({email,role,status:'Preparada'});save();closeModal();render();alert('Usuario agregado a la lista.')}
function addRecord(){if(!data.users.length)return alert('Primero agregá un usuario.');const user=prompt('Correo del usuario:');const normalized=(user||'').trim().toLowerCase();if(!data.users.some(u=>u.email===normalized))return alert('Ese usuario no existe.');const name=prompt('Nombre del registro:')||'';if(!name)return;const description=prompt('Descripción:')||'';data.records.push({user:normalized,date:new Date().toLocaleDateString('es-GT'),name,description});save();render()}
function clearAll(){if(confirm('¿Vaciar usuarios, invitaciones y registros?')){data={users:[],records:[],invites:[]};save();render()}}
render();